// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: cluster.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EndpointMain      string                 `protobuf:"bytes,1,opt,name=endpoint_main,json=endpointMain,proto3" json:"endpoint_main,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	EndpointGrpc      string                 `protobuf:"bytes,3,opt,name=endpoint_grpc,json=endpointGrpc,proto3" json:"endpoint_grpc,omitempty"`
	EndpointHttp      string                 `protobuf:"bytes,4,opt,name=endpoint_http,json=endpointHttp,proto3" json:"endpoint_http,omitempty"`
	Queue             string                 `protobuf:"bytes,5,opt,name=queue,proto3" json:"queue,omitempty"`
	Mode              string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Version           string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Health            bool                   `protobuf:"varint,8,opt,name=health,proto3" json:"health,omitempty"`
	RegisterTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	LastHeartbeatTime *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_heartbeat_time,json=lastHeartbeatTime,proto3" json:"last_heartbeat_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetEndpointMain() string {
	if x != nil {
		return x.EndpointMain
	}
	return ""
}

func (x *Node) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Node) GetEndpointGrpc() string {
	if x != nil {
		return x.EndpointGrpc
	}
	return ""
}

func (x *Node) GetEndpointHttp() string {
	if x != nil {
		return x.EndpointHttp
	}
	return ""
}

func (x *Node) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Node) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Node) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Node) GetHealth() bool {
	if x != nil {
		return x.Health
	}
	return false
}

func (x *Node) GetRegisterTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisterTime
	}
	return nil
}

func (x *Node) GetLastHeartbeatTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatTime
	}
	return nil
}

type NodesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         map[string]*Node       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesResp) Reset() {
	*x = NodesResp{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesResp) ProtoMessage() {}

func (x *NodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesResp.ProtoReflect.Descriptor instead.
func (*NodesResp) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *NodesResp) GetNodes() map[string]*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\bservices\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x02\n" +
	"\x04Node\x12#\n" +
	"\rendpoint_main\x18\x01 \x01(\tR\fendpointMain\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12#\n" +
	"\rendpoint_grpc\x18\x03 \x01(\tR\fendpointGrpc\x12#\n" +
	"\rendpoint_http\x18\x04 \x01(\tR\fendpointHttp\x12\x14\n" +
	"\x05queue\x18\x05 \x01(\tR\x05queue\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x16\n" +
	"\x06health\x18\b \x01(\bR\x06health\x12?\n" +
	"\rregister_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fregisterTime\x12J\n" +
	"\x13last_heartbeat_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x11lastHeartbeatTime\"\x8b\x01\n" +
	"\tNodesResp\x124\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1e.services.NodesResp.NodesEntryR\x05nodes\x1aH\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.services.NodeR\x05value:\x028\x012D\n" +
	"\aCluster\x129\n" +
	"\bGetNodes\x12\x16.google.protobuf.Empty\x1a\x13.services.NodesResp\"\x00B\rZ\v./;servicesb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cluster_proto_goTypes = []any{
	(*Node)(nil),                  // 0: services.Node
	(*NodesResp)(nil),             // 1: services.NodesResp
	nil,                           // 2: services.NodesResp.NodesEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_cluster_proto_depIdxs = []int32{
	3, // 0: services.Node.register_time:type_name -> google.protobuf.Timestamp
	3, // 1: services.Node.last_heartbeat_time:type_name -> google.protobuf.Timestamp
	2, // 2: services.NodesResp.nodes:type_name -> services.NodesResp.NodesEntry
	0, // 3: services.NodesResp.NodesEntry.value:type_name -> services.Node
	4, // 4: services.Cluster.GetNodes:input_type -> google.protobuf.Empty
	1, // 5: services.Cluster.GetNodes:output_type -> services.NodesResp
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
