// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: recorder.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsReq) Reset() {
	*x = RecordsReq{}
	mi := &file_recorder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsReq) ProtoMessage() {}

func (x *RecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsReq.ProtoReflect.Descriptor instead.
func (*RecordsReq) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{0}
}

func (x *RecordsReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RecordsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RecordsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RecordsAllReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsAllReq) Reset() {
	*x = RecordsAllReq{}
	mi := &file_recorder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsAllReq) ProtoMessage() {}

func (x *RecordsAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsAllReq.ProtoReflect.Descriptor instead.
func (*RecordsAllReq) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{1}
}

func (x *RecordsAllReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RecordsAllReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_recorder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Record) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Record) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Record) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Record) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Record) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type RecordsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsResp) Reset() {
	*x = RecordsResp{}
	mi := &file_recorder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsResp) ProtoMessage() {}

func (x *RecordsResp) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsResp.ProtoReflect.Descriptor instead.
func (*RecordsResp) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{3}
}

func (x *RecordsResp) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RecordsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RecordsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RecordsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_recorder_proto protoreflect.FileDescriptor

const file_recorder_proto_rawDesc = "" +
	"\n" +
	"\x0erecorder.proto\x12\bservices\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fscheduler.proto\"T\n" +
	"\n" +
	"RecordsReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"@\n" +
	"\rRecordsAllReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xe4\x01\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x125\n" +
	"\bstart_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"\x80\x01\n" +
	"\vRecordsResp\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.services.RecordR\arecords\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total2\x8d\x02\n" +
	"\bRecorder\x12;\n" +
	"\n" +
	"GetRecords\x12\x14.services.RecordsReq\x1a\x15.services.RecordsResp\"\x00\x12A\n" +
	"\rGetAllRecords\x12\x17.services.RecordsAllReq\x1a\x15.services.RecordsResp\"\x00\x12;\n" +
	"\rDeleteRecords\x12\x10.services.JobReq\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\x10DeleteAllRecords\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B\rZ\v./;servicesb\x06proto3"

var (
	file_recorder_proto_rawDescOnce sync.Once
	file_recorder_proto_rawDescData []byte
)

func file_recorder_proto_rawDescGZIP() []byte {
	file_recorder_proto_rawDescOnce.Do(func() {
		file_recorder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recorder_proto_rawDesc), len(file_recorder_proto_rawDesc)))
	})
	return file_recorder_proto_rawDescData
}

var file_recorder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_recorder_proto_goTypes = []any{
	(*RecordsReq)(nil),            // 0: services.RecordsReq
	(*RecordsAllReq)(nil),         // 1: services.RecordsAllReq
	(*Record)(nil),                // 2: services.Record
	(*RecordsResp)(nil),           // 3: services.RecordsResp
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*JobReq)(nil),                // 5: services.JobReq
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_recorder_proto_depIdxs = []int32{
	4, // 0: services.Record.start_at:type_name -> google.protobuf.Timestamp
	4, // 1: services.Record.end_at:type_name -> google.protobuf.Timestamp
	2, // 2: services.RecordsResp.records:type_name -> services.Record
	0, // 3: services.Recorder.GetRecords:input_type -> services.RecordsReq
	1, // 4: services.Recorder.GetAllRecords:input_type -> services.RecordsAllReq
	5, // 5: services.Recorder.DeleteRecords:input_type -> services.JobReq
	6, // 6: services.Recorder.DeleteAllRecords:input_type -> google.protobuf.Empty
	3, // 7: services.Recorder.GetRecords:output_type -> services.RecordsResp
	3, // 8: services.Recorder.GetAllRecords:output_type -> services.RecordsResp
	6, // 9: services.Recorder.DeleteRecords:output_type -> google.protobuf.Empty
	6, // 10: services.Recorder.DeleteAllRecords:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_recorder_proto_init() }
func file_recorder_proto_init() {
	if File_recorder_proto != nil {
		return
	}
	file_scheduler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recorder_proto_rawDesc), len(file_recorder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recorder_proto_goTypes,
		DependencyIndexes: file_recorder_proto_depIdxs,
		MessageInfos:      file_recorder_proto_msgTypes,
	}.Build()
	File_recorder_proto = out.File
	file_recorder_proto_goTypes = nil
	file_recorder_proto_depIdxs = nil
}
