// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: scheduler.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobReq) Reset() {
	*x = JobReq{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobReq) ProtoMessage() {}

func (x *JobReq) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobReq.ProtoReflect.Descriptor instead.
func (*JobReq) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *JobReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StartAt       string                 `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         string                 `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Interval      string                 `protobuf:"bytes,6,opt,name=interval,proto3" json:"interval,omitempty"`
	CronExpr      string                 `protobuf:"bytes,7,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	Timezone      string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	FuncName      string                 `protobuf:"bytes,9,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	Args          *structpb.Struct       `protobuf:"bytes,10,opt,name=args,proto3" json:"args,omitempty"`
	Timeout       string                 `protobuf:"bytes,11,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Queues        []string               `protobuf:"bytes,12,rep,name=queues,proto3" json:"queues,omitempty"`
	MaxInstances  int32                  `protobuf:"varint,13,opt,name=max_instances,json=maxInstances,proto3" json:"max_instances,omitempty"`
	LastRunTime   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	NextRunTime   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time,omitempty"`
	Status        string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *Job) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *Job) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Job) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *Job) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Job) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *Job) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Job) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Job) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *Job) GetMaxInstances() int32 {
	if x != nil {
		return x.MaxInstances
	}
	return 0
}

func (x *Job) GetLastRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunTime
	}
	return nil
}

func (x *Job) GetNextRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunTime
	}
	return nil
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JobsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobsResp) Reset() {
	*x = JobsResp{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobsResp) ProtoMessage() {}

func (x *JobsResp) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobsResp.ProtoReflect.Descriptor instead.
func (*JobsResp) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *JobsResp) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\bservices\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x06JobReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xfd\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\tR\astartAt\x12\x15\n" +
	"\x06end_at\x18\x05 \x01(\tR\x05endAt\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\tR\binterval\x12\x1b\n" +
	"\tcron_expr\x18\a \x01(\tR\bcronExpr\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12\x1b\n" +
	"\tfunc_name\x18\t \x01(\tR\bfuncName\x12+\n" +
	"\x04args\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x04args\x12\x18\n" +
	"\atimeout\x18\v \x01(\tR\atimeout\x12\x16\n" +
	"\x06queues\x18\f \x03(\tR\x06queues\x12#\n" +
	"\rmax_instances\x18\r \x01(\x05R\fmaxInstances\x12>\n" +
	"\rlast_run_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vlastRunTime\x12>\n" +
	"\rnext_run_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vnextRunTime\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\"-\n" +
	"\bJobsResp\x12!\n" +
	"\x04jobs\x18\x01 \x03(\v2\r.services.JobR\x04jobs2\x86\x05\n" +
	"\tScheduler\x12(\n" +
	"\x06AddJob\x12\r.services.Job\x1a\r.services.Job\"\x00\x12+\n" +
	"\x06GetJob\x12\x10.services.JobReq\x1a\r.services.Job\"\x00\x12:\n" +
	"\n" +
	"GetAllJobs\x12\x16.google.protobuf.Empty\x1a\x12.services.JobsResp\"\x00\x12+\n" +
	"\tUpdateJob\x12\r.services.Job\x1a\r.services.Job\"\x00\x127\n" +
	"\tDeleteJob\x12\x10.services.JobReq\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\rDeleteAllJobs\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\bPauseJob\x12\x10.services.JobReq\x1a\r.services.Job\"\x00\x12.\n" +
	"\tResumeJob\x12\x10.services.JobReq\x1a\r.services.Job\"\x00\x121\n" +
	"\x06RunJob\x12\r.services.Job\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\vScheduleJob\x12\r.services.Job\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\x05Start\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x128\n" +
	"\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B\rZ\v./;servicesb\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_scheduler_proto_goTypes = []any{
	(*JobReq)(nil),                // 0: services.JobReq
	(*Job)(nil),                   // 1: services.Job
	(*JobsResp)(nil),              // 2: services.JobsResp
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_scheduler_proto_depIdxs = []int32{
	3,  // 0: services.Job.args:type_name -> google.protobuf.Struct
	4,  // 1: services.Job.last_run_time:type_name -> google.protobuf.Timestamp
	4,  // 2: services.Job.next_run_time:type_name -> google.protobuf.Timestamp
	1,  // 3: services.JobsResp.jobs:type_name -> services.Job
	1,  // 4: services.Scheduler.AddJob:input_type -> services.Job
	0,  // 5: services.Scheduler.GetJob:input_type -> services.JobReq
	5,  // 6: services.Scheduler.GetAllJobs:input_type -> google.protobuf.Empty
	1,  // 7: services.Scheduler.UpdateJob:input_type -> services.Job
	0,  // 8: services.Scheduler.DeleteJob:input_type -> services.JobReq
	5,  // 9: services.Scheduler.DeleteAllJobs:input_type -> google.protobuf.Empty
	0,  // 10: services.Scheduler.PauseJob:input_type -> services.JobReq
	0,  // 11: services.Scheduler.ResumeJob:input_type -> services.JobReq
	1,  // 12: services.Scheduler.RunJob:input_type -> services.Job
	1,  // 13: services.Scheduler.ScheduleJob:input_type -> services.Job
	5,  // 14: services.Scheduler.Start:input_type -> google.protobuf.Empty
	5,  // 15: services.Scheduler.Stop:input_type -> google.protobuf.Empty
	1,  // 16: services.Scheduler.AddJob:output_type -> services.Job
	1,  // 17: services.Scheduler.GetJob:output_type -> services.Job
	2,  // 18: services.Scheduler.GetAllJobs:output_type -> services.JobsResp
	1,  // 19: services.Scheduler.UpdateJob:output_type -> services.Job
	5,  // 20: services.Scheduler.DeleteJob:output_type -> google.protobuf.Empty
	5,  // 21: services.Scheduler.DeleteAllJobs:output_type -> google.protobuf.Empty
	1,  // 22: services.Scheduler.PauseJob:output_type -> services.Job
	1,  // 23: services.Scheduler.ResumeJob:output_type -> services.Job
	5,  // 24: services.Scheduler.RunJob:output_type -> google.protobuf.Empty
	5,  // 25: services.Scheduler.ScheduleJob:output_type -> google.protobuf.Empty
	5,  // 26: services.Scheduler.Start:output_type -> google.protobuf.Empty
	5,  // 27: services.Scheduler.Stop:output_type -> google.protobuf.Empty
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
