version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 127.0.0.1:3306:3306

  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379

  mongodb:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
