# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x08services\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n\x05JobId\x12\n\n\x02id\x18\x01 \x01(\t\"\xd7\x02\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08start_at\x18\x04 \x01(\t\x12\x0e\n\x06\x65nd_at\x18\x05 \x01(\t\x12\x10\n\x08interval\x18\x06 \x01(\t\x12\x11\n\tcron_expr\x18\x07 \x01(\t\x12\x10\n\x08timezone\x18\x08 \x01(\t\x12\x11\n\tfunc_name\x18\t \x01(\t\x12%\n\x04\x61rgs\x18\n \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07timeout\x18\x0b \x01(\t\x12\x0e\n\x06queues\x18\x0c \x03(\t\x12\x31\n\rlast_run_time\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rnext_run_time\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06status\x18\x0f \x01(\t\"#\n\x04Jobs\x12\x1b\n\x04jobs\x18\x01 \x03(\x0b\x32\r.services.Job2\xfe\x04\n\tScheduler\x12(\n\x06\x41\x64\x64Job\x12\r.services.Job\x1a\r.services.Job\"\x00\x12*\n\x06GetJob\x12\x0f.services.JobId\x1a\r.services.Job\"\x00\x12\x36\n\nGetAllJobs\x12\x16.google.protobuf.Empty\x1a\x0e.services.Jobs\"\x00\x12+\n\tUpdateJob\x12\r.services.Job\x1a\r.services.Job\"\x00\x12\x36\n\tDeleteJob\x12\x0f.services.JobId\x1a\x16.google.protobuf.Empty\"\x00\x12\x41\n\rDeleteAllJobs\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12,\n\x08PauseJob\x12\x0f.services.JobId\x1a\r.services.Job\"\x00\x12-\n\tResumeJob\x12\x0f.services.JobId\x1a\r.services.Job\"\x00\x12\x31\n\x06RunJob\x12\r.services.Job\x1a\x16.google.protobuf.Empty\"\x00\x12\x36\n\x0bScheduleJob\x12\r.services.Job\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\x05Start\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x38\n\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x42\rZ\x0b./;servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./;services'
  _globals['_JOBID']._serialized_start=121
  _globals['_JOBID']._serialized_end=140
  _globals['_JOB']._serialized_start=143
  _globals['_JOB']._serialized_end=486
  _globals['_JOBS']._serialized_start=488
  _globals['_JOBS']._serialized_end=523
  _globals['_SCHEDULER']._serialized_start=526
  _globals['_SCHEDULER']._serialized_end=1164
# @@protoc_insertion_point(module_scope)
