# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recorder.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import scheduler_pb2 as scheduler__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erecorder.proto\x12\x08services\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fscheduler.proto\"=\n\nRecordsReq\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"0\n\rRecordsAllReq\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"\xb0\x01\n\x06Record\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x10\n\x08job_name\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0e\n\x06result\x18\x05 \x01(\t\x12,\n\x08start_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06\x65nd_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"`\n\x0bRecordsResp\x12!\n\x07records\x18\x01 \x03(\x0b\x32\x10.services.Record\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\r\n\x05total\x18\x04 \x01(\x03\x32\x8d\x02\n\x08Recorder\x12;\n\nGetRecords\x12\x14.services.RecordsReq\x1a\x15.services.RecordsResp\"\x00\x12\x41\n\rGetAllRecords\x12\x17.services.RecordsAllReq\x1a\x15.services.RecordsResp\"\x00\x12;\n\rDeleteRecords\x12\x10.services.JobReq\x1a\x16.google.protobuf.Empty\"\x00\x12\x44\n\x10\x44\x65leteAllRecords\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x42\rZ\x0b./;servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recorder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./;services'
  _globals['_RECORDSREQ']._serialized_start=107
  _globals['_RECORDSREQ']._serialized_end=168
  _globals['_RECORDSALLREQ']._serialized_start=170
  _globals['_RECORDSALLREQ']._serialized_end=218
  _globals['_RECORD']._serialized_start=221
  _globals['_RECORD']._serialized_end=397
  _globals['_RECORDSRESP']._serialized_start=399
  _globals['_RECORDSRESP']._serialized_end=495
  _globals['_RECORDER']._serialized_start=498
  _globals['_RECORDER']._serialized_end=767
# @@protoc_insertion_point(module_scope)
