version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=agscheduler
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 127.0.0.1:3306:3306

  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379

  mongodb:
    image: mongo:4.4.29
    ports:
      - 127.0.0.1:27017:27017

  etcd:
    image: docker.io/bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 127.0.0.1:2379:2379

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 127.0.0.1:9200:9200
