version: "3"
services:
  nsqd:
    image: nsqio/nsq
    command: /nsqd
    ports:
      - 127.0.0.1:4150:4150
      - 127.0.0.1:4151:4151

  rabbitmq:
    image: rabbitmq
    ports:
      - 127.0.0.1:5672:5672

  nanomq:
    image: emqx/nanomq
    ports:
      - 127.0.0.1:1883:1883

  kafka:
    image: apache/kafka
    ports:
      - 127.0.0.1:9092:9092
