name: test

on:
  push:
    branches: ["main", "test", "dev", "dev/*", "dev_*"]
  pull_request:
    branches: ["main", "test", "dev"]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Start external services
      run: |
        make up-ci-services
  
    - name: Install dependencies
      run: |
        make install

    - name: Format with gofmt
      run: |
        make format-check

    - name: Lint with golangci-lint
      run: |
        make lint

    - name: Test with go test
      run: |
        ./ci/wait-for-it.sh 127.0.0.1:3306 -s -t 60
        sleep 10
        make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
